#!/bin/bash

# Before using django-admin.py, virtualenv should be activate.
DJANGO_ADMIN=django-admin.py
PYTHONPATH=`pwd`
DJANGO_SETTINGS_MODULE=souche.settings.dev

ARG_PYTHONPATH="--pythonpath=$PYTHONPATH"
ARG_SETTINGS="--settings=$DJANGO_SETTINGS_MODULE"

COMMANDS="shell runserver sql syncdb"


function runserver_proc()
{
    $DJANGO_ADMIN runserver 0.0.0.0:9000 $ARG_SETTINGS $ARG_PYTHONPATH
}

function shell_proc()
{
    $DJANGO_ADMIN shell $ARG_SETTINGS $ARG_PYTHONPATH
}

function sql_proc()
{
    $DJANGO_ADMIN sql $1 $ARG_SETTINGS $ARG_PYTHONPATH
}

function syncdb_proc()
{
    $DJANGO_ADMIN syncdb $ARG_SETTINGS $ARG_PYTHONPATH
}


function run_command()
{
    command_name="$1"
    found=false
    for command in $COMMANDS
    do
        if [ "$command" == "$command_name" ]
        then
            proc_name="${command}_proc"
            $proc_name $2
            found=true
        fi
    done

    if [ ! $found ]
    then
        echo "Unknown command. runserver --help to get usage."
        exit 1
    fi
}

function usage()
{
    echo
    echo "runserver [$COMMANDS]"
}

case $1 in
    -h | --help | help)
        usage ;;
    *)
        if [ -n "$1" ]
        then
            run_command $1 $2
        else
            usage
        fi
        ;;
esac
